### ISSUE TITLE
Pinging External IPs

### ISSUE THREAD

**Issue by lancekavalsky** [ArjunaCluster/HerculesUsers#2]
Recently our installation of [fireworks](https://materialsproject.github.io/fireworks/index.html) has started exhibiting connection issues to external mongoDB servers which weren't observed previously.

We noticed that while `ping 8.8.8.8` works, `ping google.com` doesn't and just gives:
```
ping: google.com: Name or service not known
```

To provide an additional MWE from the fireworks side, the [Testing connection to a remote server](https://materialsproject.github.io/fireworks/installation.html#testing-connection-to-a-remote-server) section of the fireworks docs no longer works and provides the following error message:

```
Traceback (most recent call last):
  File "/home/aced/.conda/envs/autocat_gpaw2/bin/lpad", line 8, in <module>
    sys.exit(lpad())
  File "/home/aced/.conda/envs/autocat_gpaw2/lib/python3.7/site-packages/fireworks/scripts/lpad_run.py", line 1209, in lpad
    args.func(args)
  File "/home/aced/.conda/envs/autocat_gpaw2/lib/python3.7/site-packages/fireworks/scripts/lpad_run.py", line 322, in get_wfs
    ids = lp.get_wf_ids(query, sort, args.max, count_only=args.display_format == 'count')
  File "/home/aced/.conda/envs/autocat_gpaw2/lib/python3.7/site-packages/fireworks/core/launchpad.py", line 768, in get_wf_ids
    sort=sort).limit(limit):
  File "/home/aced/.conda/envs/autocat_gpaw2/lib/python3.7/site-packages/pymongo/cursor.py", line 1207, in next
    if len(self.__data) or self._refresh():
  File "/home/aced/.conda/envs/autocat_gpaw2/lib/python3.7/site-packages/pymongo/cursor.py", line 1100, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "/home/aced/.conda/envs/autocat_gpaw2/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1816, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/home/aced/.conda/envs/autocat_gpaw2/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1766, in __start_session
    server_session = self._get_server_session()
  File "/home/aced/.conda/envs/autocat_gpaw2/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1802, in _get_server_session
    return self._topology.get_server_session()
  File "/home/aced/.conda/envs/autocat_gpaw2/lib/python3.7/site-packages/pymongo/topology.py", line 488, in get_server_session
    None)
  File "/home/aced/.conda/envs/autocat_gpaw2/lib/python3.7/site-packages/pymongo/topology.py", line 217, in _select_servers_loop
    (self._error_message(selector), timeout, self.description))
pymongo.errors.ServerSelectionTimeoutError: ds049170.mongolab.com:49170: [Errno -2] Name or service not known, Timeout: 30s, Topology Description: <TopologyDescription id: 6123eae1b476f6cb42063cdc, topology_type: Single, servers: [<ServerDescription ('ds049170.mongolab.com', 49170) server_type: Unknown, rtt: None, error=AutoReconnect('ds049170.mongolab.com:49170: [Errno -2] Name or service not known')>]>
```

Not sure if something about the cluster's connectivity has changed recently. Any advice would be much appreciated.

Thanks!

**Comment by aabills** [comment]
Dang, I fixed this a while ago, looks like it wasn't persistent on reboot.  I changed it a smarter way this time, so it should be persistent.
